services:
  caddy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports: [8443:443]
  bunproxy:
    restart: always
    build: .
    image: snomiao/bunproxy
    # dev
    working_dir: /app
    command: bun --hot /app/index.ts
    volumes:
      - ./:/app
  nginx:
    image: nginx
  pong:
    image: caddy
    command: caddy respond --listen :2000-2004 "I'm server {{.N}} on port {{.Port}}"
